In [2]:
import numpy as np
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
file_path = '/content/drive/MyDrive/Machine Learning/fire-occurence.csv'

df = pd.read_csv(file_path)

In [5]:
df.head()

,Serial,FireCategory,FireYear,Area,DistrictName,UnitName,FullFireNumber,FireName,Size_class,EstTotalAcres,...,Industrial_Restriction,Ign_DateTime,ReportDateTime,Discover_DateTime,Control_DateTime,CreationDate,ModifiedDate,DistrictCode,UnitCode,DistFireNumber
0,58256,STAT,2000,EOA,Central Oregon,John Day,00-952011-01,Slick Ear #2,B,0.75,...,Does Not Apply - Eastern OR,07/18/2000 07:00:00 PM,07/19/2000 01:20:00 PM,07/19/2000 01:15:00 PM,07/20/2000 12:50:00 AM,07/20/2000 09:13:00 AM,11/14/2000 09:16:00 AM,95,952,011
1,59312,STAT,2000,EOA,Northeast Oregon,La Grande,00-971024-01,Woodley,C,80.00,...,Does Not Apply - Eastern OR,08/24/2000 05:30:00 AM,08/24/2000 01:07:00 PM,08/24/2000 01:07:00 PM,09/01/2000 09:30:00 PM,08/29/2000 03:59:00 PM,12/21/2000 04:22:00 PM,97,971,024
2,61657,STAT,2001,SOA,Southwest Oregon,Grants Pass,01-712133-02,QUEENS BRANCH,A,0.10,...,Lvl 3 Restricted Shutdown,08/10/2001 05:40:00 PM,08/10/2001 05:47:00 PM,08/10/2001 05:45:00 PM,08/10/2001 06:30:00 PM,08/10/2001 06:42:00 PM,08/17/2001 11:45:00 AM,71,712,133
3,63735,STAT,2002,NOA,West Oregon,Philomath,02-551001-03,WREN,A,0.01,...,Lvl 1 Fire Season Only,07/06/2002 01:01:00 PM,07/06/2002 01:04:00 PM,07/06/2002 01:02:00 PM,07/06/2002 01:07:00 PM,07/07/2002 09:16:00 AM,07/28/2002 10:08:00 AM,55,551,001
4,68019,STAT,2003,NOA,West Oregon,Dallas,03-552013-04,Ritner Creek,A,0.01,...,Lvl 3 Restricted Shutdown,08/22/2003 04:00:00 AM,08/22/2003 05:00:00 AM,08/22/2003 05:00:00 AM,08/22/2003 09:30:00 AM,08/22/2003 04:12:00 PM,09/04/2003 09:39:00 AM,55,552,013

In [6]:
df.isnull().sum()

Serial                        0
FireCategory                  0
FireYear                      0
Area                          0
DistrictName                  0
UnitName                      0
FullFireNumber                0
FireName                      0
Size_class                    0
EstTotalAcres                79
Protected_Acres               0
HumanOrLightning              0
CauseBy                     128
GeneralCause                  0
SpecificCause               224
Cause_Comments            13685
Lat_DD                       10
Long_DD                      10
LatLongDD                    10
FO_LandOwnType                0
Twn                          12
Rng                          15
Sec                          12
Subdiv                       31
LandmarkLocation           1282
County                        0
RegUseZone                   50
RegUseRestriction            89
Industrial_Restriction       89
Ign_DateTime                 94
ReportDateTime                0
Discover_DateTime            94
Control_DateTime             95
CreationDate                  3
ModifiedDate                  0
DistrictCode                  0
UnitCode                      0
DistFireNumber                0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23490 entries, 0 to 23489
Data columns (total 38 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Serial                  23490 non-null  int64
 1   FireCategory            23490 non-null  object
 2   FireYear                23490 non-null  int64
 3   Area                    23490 non-null  object
 4   DistrictName            23490 non-null  object
 5   UnitName                23490 non-null  object
 6   FullFireNumber          23490 non-null  object
 7   FireName                23490 non-null  object
 8   Size_class              23490 non-null  object
 9   EstTotalAcres           23411 non-null  float64
 10  Protected_Acres         23490 non-null  float64
 11  HumanOrLightning        23490 non-null  object
 12  CauseBy                 23362 non-null  object
 13  GeneralCause            23490 non-null  object
 14  SpecificCause           23266 non-null  object
 15  Cause_Comments          9805 non-null   object
 16  Lat_DD                  23480 non-null  float64
 17  Long_DD                 23480 non-null  float64
 18  LatLongDD               23480 non-null  object
 19  FO_LandOwnType          23490 non-null  object
 20  Twn                     23478 non-null  object
 21  Rng                     23475 non-null  object
 22  Sec                     23478 non-null  float64
 23  Subdiv                  23459 non-null  object
 24  LandmarkLocation        22208 non-null  object
 25  County                  23490 non-null  object
 26  RegUseZone              23440 non-null  object
 27  RegUseRestriction       23401 non-null  object
 28  Industrial_Restriction  23401 non-null  object
 29  Ign_DateTime            23396 non-null  object
 30  ReportDateTime          23490 non-null  object
 31  Discover_DateTime       23396 non-null  object
 32  Control_DateTime        23395 non-null  object
 33  CreationDate            23487 non-null  object
 34  ModifiedDate            23490 non-null  object
 35  DistrictCode            23490 non-null  int64
 36  UnitCode                23490 non-null  int64
 37  DistFireNumber          23490 non-null  object
dtypes: float64(5), int64(4), object(29)
memory usage: 6.8+ MB

In [8]:
leakage_columns = ['Size_class', 'Control_DateTime']
useless_columns = [
    'Serial', 'FullFireNumber', 'FireName', 'Cause_Comments',
    'LandmarkLocation', 'DistrictCode', 'UnitCode', 'DistFireNumber',
    'CreationDate', 'ModifiedDate'
]
df = df.drop(columns=leakage_columns + useless_columns, errors='ignore')

df = df.dropna(subset=['EstTotalAcres'])
df['Ign_DateTime'] = pd.to_datetime(df['Ign_DateTime'], errors='coerce')
df = df.dropna(subset=['Ign_DateTime'])
df['Ign_Month'] = df['Ign_DateTime'].dt.month
df['Ign_Hour'] = df['Ign_DateTime'].dt.hour
time_columns_to_drop = ['Ign_DateTime', 'ReportDateTime', 'Discover_DateTime']
df = df.drop(columns=time_columns_to_drop, errors='ignore')
df = df.dropna()

/tmp/ipykernel_283/3470852512.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Ign_DateTime'] = pd.to_datetime(df['Ign_DateTime'], errors='coerce')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23202 entries, 0 to 23489
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   FireCategory            23202 non-null  object
 1   FireYear                23202 non-null  int64
 2   Area                    23202 non-null  object
 3   DistrictName            23202 non-null  object
 4   UnitName                23202 non-null  object
 5   EstTotalAcres           23202 non-null  float64
 6   Protected_Acres         23202 non-null  float64
 7   HumanOrLightning        23202 non-null  object
 8   CauseBy                 23202 non-null  object
 9   GeneralCause            23202 non-null  object
 10  SpecificCause           23202 non-null  object
 11  Lat_DD                  23202 non-null  float64
 12  Long_DD                 23202 non-null  float64
 13  LatLongDD               23202 non-null  object
 14  FO_LandOwnType          23202 non-null  object
 15  Twn                     23202 non-null  object
 16  Rng                     23202 non-null  object
 17  Sec                     23202 non-null  float64
 18  Subdiv                  23202 non-null  object
 19  County                  23202 non-null  object
 20  RegUseZone              23202 non-null  object
 21  RegUseRestriction       23202 non-null  object
 22  Industrial_Restriction  23202 non-null  object
 23  Ign_Month               23202 non-null  int32
 24  Ign_Hour                23202 non-null  int32
dtypes: float64(5), int32(2), int64(1), object(17)
memory usage: 4.4+ MB

In [15]:
# Convert categorical variables into dummy/indicator variables
df = pd.get_dummies(df, drop_first=True)

# Check the updated dataframe structure
df.info()
display(df.head())

<class 'pandas.core.frame.DataFrame'>
Index: 23202 entries, 0 to 23489
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   FireCategory            23202 non-null  int64
 1   FireYear                23202 non-null  int64
 2   Area                    23202 non-null  int64
 3   DistrictName            23202 non-null  int64
 4   UnitName                23202 non-null  int64
 5   EstTotalAcres           23202 non-null  float64
 6   Protected_Acres         23202 non-null  float64
 7   HumanOrLightning        23202 non-null  int64
 8   CauseBy                 23202 non-null  int64
 9   GeneralCause            23202 non-null  int64
 10  SpecificCause           23202 non-null  int64
 11  Lat_DD                  23202 non-null  float64
 12  Long_DD                 23202 non-null  float64
 13  LatLongDD               23202 non-null  int64
 14  FO_LandOwnType          23202 non-null  int64
 15  Twn                     23202 non-null  int64
 16  Rng                     23202 non-null  int64
 17  Sec                     23202 non-null  float64
 18  Subdiv                  23202 non-null  int64
 19  County                  23202 non-null  int64
 20  RegUseZone              23202 non-null  int64
 21  RegUseRestriction       23202 non-null  int64
 22  Industrial_Restriction  23202 non-null  int64
 23  Ign_Month               23202 non-null  int32
 24  Ign_Hour                23202 non-null  int32
dtypes: float64(5), int32(2), int64(18)
memory usage: 4.4 MB

,FireCategory,FireYear,Area,DistrictName,UnitName,EstTotalAcres,Protected_Acres,HumanOrLightning,CauseBy,GeneralCause,...,Twn,Rng,Sec,Subdiv,County,RegUseZone,RegUseRestriction,Industrial_Restriction,Ign_Month,Ign_Hour
0,0,2000,0,1,14,0.75,0.75,1,3,4,...,14,67,31.0,7,11,24,4,0,7,19
1,0,2000,0,7,16,80.00,80.00,1,3,4,...,10,79,32.0,7,30,49,4,0,8,5
2,0,2001,2,9,13,0.10,0.10,0,5,8,...,71,7,7.0,16,14,75,4,3,8,17
3,0,2002,1,12,21,0.01,0.01,0,5,7,...,21,13,28.0,15,1,85,1,1,7,13
4,0,2003,1,12,9,0.01,0.01,1,3,4,...,18,21,36.0,22,27,99,4,3,8,4